@startuml broadcast-write
title <color red><size:25>Spark broadcast write</size></color>
SparkContext -> SparkContext: broadcast
SparkContext -> BroadcastManager: newBroadcast
BroadcastManager -> TorrentBroadcastFactory: newBroadcast
TorrentBroadcastFactory -> TorrentBroadcast: writeBlocks
TorrentBroadcast -> BlockManager: putBytes (<color red>final write driver BlockManager</color>)
@enduml

@startuml broadcast-read
title <color red><size:25>Spark broadcast read</size></color>
SparkContext -> SparkContext: broadcast
SparkContext -> Broadcast: getValue
Broadcast -> TorrentBroadcast: readBroadcastBlock
TorrentBroadcast -> TorrentBroadcast: readBlocks
TorrentBroadcast -> BlockManager: getRemoteBytes
BlockManager -> BlockManager: getRemoteBlock
BlockManager -> BlockManagerMasterEndpoint: getLocationsAndStatus
BlockManagerMasterEndpoint -> BlockManager: Option[BlockLocationsAndStatus]
BlockManager -> BlockManager: Option[T]
BlockManager -> TorrentBroadcast: Array[BlockData]
TorrentBroadcast -> TorrentBroadcast: T (<color red>final data type</color>)
TorrentBroadcast -> Broadcast: T
Broadcast -> SparkContext: T
@enduml